### ISSUE TITLE
Build is not working due to missing files 

### ISSUE THREAD

**Issue by TortugaAttack** [antonioillera/iHDTpp-src#1]
Building HDT++ is not working due to the following missing files

Files missing and workaround which worked for me
```
libcds/tests/Makefile.am #works with the one from hdt c++
libhdt/tests/Makefile.am #works with the one from hdt c++
libhdt/tools/testhdt.cpp #commented out in libhdt/tools/Makefile.am seem to work
libhdt/tools/testhdtpp.cpp #commented out in libhdt/tools/Makefile.am seem to work
```

Further on libsdsl/lib/sdsl.a was missing 
But installing it with https://github.com/simongog/sdsl-lite worked 
```
./install.sh ${iHDTpp-src}/libsdsl/
```

This worked in my local Arch Linux machine at least

However on a 
Ubuntu 16.4 with Linux 4.4.0-137-generic 
make 4.1
automake 1.15
autoconf 2.69
it builds with the workarounds, but throws a  `Speicherzugriffsfehler (Speicherabzug geschrieben)` if executing `hdt2hdtpp`
which translates too a segmentation fault.

**Comment by antonioillera** [comment]
Hi, Félix 

Makefiles are available and fixed now. Regarding the segmentation fault, Could you provide the dataset you are using, to review the issue?

Thank you

**Comment by TortugaAttack** [comment]
Thanks for the fast response. :)

Dataset is attached. However i tried multiple ones and all of them caused the seg fault
[external_links.zip](https://github.com/antonioillera/iHDTpp-src/files/4515595/external_links.zip)

**Comment by antonioillera** [comment]
Hi, Felix.

Despite the error (possibly some previously deleted pointer), the HDT++ file is generated. As I review that error, could you confirm that it generates the file for you too? The HDT++ file should be operational.

**Comment by TortugaAttack** [comment]
Hi, 
Yes indeed the file is created. 
and it is operational. 
Thanks a lot. :)

**Comment by TortugaAttack** [comment]
However the HDT++ file is a bit larger than the original HDT file. Is that correct? (The file is rather small so might be that)

**Comment by antonioillera** [comment]
Yes, that is because of the small size of the dataset. :)

**Comment by antonioillera** [comment]
I am pretty sure the error you get is thrown by the original HDT library because there are no shared terms in your dataset (playing subject and object rol). I'll try to get in touch with them to fix it,

**Comment by TortugaAttack** [comment]
perfect, 
thanks a lot for the help
